apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: example # this should match the selector in service.yml
    spec:
      containers:
        - name: example
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - APP_COOKIE_NAME: ${{ secrets.APP_COOKIE_NAME }}
            - APP_COOKIE_SECRET: ${{ secrets.APP_COOKIE_SECRET }}
            - APP_SEARCH_PAGINATION_ITEMS_PER_PAGE: ${{ vars.APP_SEARCH_PAGINATION_ITEMS_PER_PAGE }}
            - APP_DOCUMENT_PAGINATION_ITEMS_PER_PAGE: ${{ vars.APP_DOCUMENT_PAGINATION_ITEMS_PER_PAGE }}
            - APP_API_URL: ${{ vars.APP_API_URL }}
