apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: example # this should match the selector in service.yml
    spec:
      containers:
        - name: example
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
        - ports:
            - containerPort: 8080
        - env:
            - name: APP_COOKIE_NAME
              value: ${ secrets.APP_COOKIE_NAME }
            - name: APP_COOKIE_SECRET
              value: ${ secrets.APP_COOKIE_SECRET }
            - name: APP_SEARCH_PAGINATION_ITEMS_PER_PAGE
              value: ${ secrets.APP_SEARCH_PAGINATION_ITEMS_PER_PAGE }
            - name: APP_DOCUMENT_PAGINATION_ITEMS_PER_PAGE
              value: ${ secrets.APP_DOCUMENT_PAGINATION_ITEMS_PER_PAGE }
            - name: APP_API_URL
              value: ${ secrets.APP_API_URL }
