apiVersion: v1
kind: Service
metadata:
  name: cica-case-review-documents-service
  labels:
    app: cica-case-review-documents-service
spec:
  selector:
    app: cica-case-review-documents # this should match the pod label in deployment.yml
  ports:
    - name: https
      port: 5000
      targetPort: 8080